#!/usr/bin/env tsx
// ── D1 seed script ────────────────────────────────────────────────────────────
//
// Reads data/rwha.json, generates a SQL seed file, and optionally executes it
// against a local or remote D1 database.
//
// Usage:
//   npm run db:seed              # generates scripts/seed.sql
//   npm run db:seed -- --local   # generates + executes against local D1
//   npm run db:seed -- --remote  # generates + executes against remote D1
//
// The generated seed.sql can also be manually applied with:
//   npx wrangler d1 execute rwha-sim --local  --file=scripts/seed.sql
//   npx wrangler d1 execute rwha-sim          --file=scripts/seed.sql

import { execSync }   from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { loadLeague }    from '../src/data.ts';
import { generateSchedule } from '../src/schedule.ts';

// ── Config ───────────────────────────────────────────────────────────────────
const SEASON_NAME = '2025-26';

// Commissioner emails — these accounts can run games.
// NOT committed to env vars; just identifiers matching Cloudflare Access users.
const COMMISSIONER_EMAILS = new Set([
  'turner@turnerholdings.com',   // Dean
  'trevorjmack@gmail.com',       // Trevor
]);

const SCHEDULE_SEED = 1;   // reproducible schedule

// ── Helpers ───────────────────────────────────────────────────────────────────
function esc(s: string | null | undefined): string {
  if (s === null || s === undefined) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function num(n: number | null | undefined): string {
  return n === null || n === undefined ? 'NULL' : String(n);
}

// ── Build SQL ─────────────────────────────────────────────────────────────────
function buildSql(): string {
  const lines: string[] = [];
  const out = (s: string) => lines.push(s);

  out('-- Auto-generated by scripts/seed.ts');
  out('-- Wipe and re-seed:');
  out('--   npx wrangler d1 execute rwha-sim --local --file=scripts/seed.sql');
  out('');
  out('PRAGMA foreign_keys = OFF;');
  out('DELETE FROM team_lines;');
  out('DELETE FROM skater_game_stats;');
  out('DELETE FROM goalie_game_stats;');
  out('DELETE FROM game_results;');
  out('DELETE FROM scheduled_games;');
  out('DELETE FROM players;');
  out('DELETE FROM teams;');
  out('DELETE FROM seasons;');
  out('PRAGMA foreign_keys = ON;');
  out('');

  // ── Season ────────────────────────────────────────────────────────────────
  out(`INSERT INTO seasons (id, name, status) VALUES (1, ${esc(SEASON_NAME)}, 'active');`);
  out('');

  // ── Teams + Players ───────────────────────────────────────────────────────
  const league = loadLeague();
  const teams  = [...league.teams.values()];
  const teamIdMap = new Map<string, number>();  // name → DB id
  let teamId   = 1;
  let playerId = 1;

  out('-- Teams');
  for (const team of teams) {
    teamIdMap.set(team.name, teamId);
    const isCommish = COMMISSIONER_EMAILS.has(team.gm.split('<')[1]?.replace('>', '') ?? '')
      || team.gm.toLowerCase().includes('dean')
      || team.gm.toLowerCase().includes('trevor')
      ? 0 : 0;  // resolved below via email match

    // We can't know gm_email from the JSON — it's just gm_name there.
    // We seed gm_email as a placeholder; the GM updates it on first login
    // OR the commissioner sets it in /admin.  Dean and Trevor's teams are
    // identified by matching against COMMISSIONER_EMAILS at setup time.
    // For now: leave gm_email as empty; the commissioner can fill it in
    // via the admin UI.  is_commissioner is set for the two known teams below.
    out(`INSERT INTO teams (id, season_id, name, gm_name, gm_email, farm_name, is_commissioner)`);
    out(`  VALUES (${teamId}, 1, ${esc(team.name)}, ${esc(team.gm)}, '', ${esc(team.farmName)}, 0);`);
    teamId++;
  }
  out('');

  // Set commissioner flag for Dean + Trevor — we do it by updating their teams
  // after we know which team each GM manages. For the seed, we mark the two
  // teams that Dean (Warheads) and Trevor (Oilers) manage. These are updated
  // via the admin UI if the team assignments change.
  // NOTE: Update these team names if the GM assignments change.
  out("-- Commissioner flags (update team names here if GMs change teams)");
  out(`UPDATE teams SET gm_email = 'turner@turnerholdings.com', is_commissioner = 1`);
  out(`  WHERE season_id = 1 AND name = (SELECT name FROM teams WHERE season_id = 1 AND gm_name LIKE '%Dean%' LIMIT 1);`);
  out(`UPDATE teams SET gm_email = 'trevorjmack@gmail.com',    is_commissioner = 1`);
  out(`  WHERE season_id = 1 AND name = (SELECT name FROM teams WHERE season_id = 1 AND gm_name LIKE '%Trevor%' LIMIT 1);`);
  out('');

  out('-- Players');
  for (const team of teams) {
    const tid = teamIdMap.get(team.name)!;

    const insertPlayer = (player: typeof team.proSkaters[0], level: string, isGoalie: boolean) => {
      const attrs = JSON.stringify(player.attrs ?? (player as any).attrs ?? {});
      out(`INSERT INTO players (id, team_id, name, position, is_goalie, ov, attrs, age, contract_yrs, salary, roster_level, is_scratch)`);
      out(`  VALUES (${playerId++}, ${tid}, ${esc(player.name)}, ${esc(player.position ?? (player as any).position ?? 'G')}, ${isGoalie ? 1 : 0}, ${player.ov}, ${esc(attrs)}, ${num((player as any).age)}, ${num((player as any).contractYears)}, ${num((player as any).salary)}, ${esc(level)}, 0);`);
    };

    for (const s of team.proSkaters)   insertPlayer(s as any, 'pro',  false);
    for (const g of team.proGoalies)   insertPlayer(g as any, 'pro',  true);
    for (const s of team.farmSkaters)  insertPlayer(s as any, 'farm', false);
    for (const g of team.farmGoalies)  insertPlayer(g as any, 'farm', true);
  }
  out('');

  // ── Schedule ──────────────────────────────────────────────────────────────
  out('-- Schedule (82 games per team, 902 total)');
  const teamNames = teams.map(t => t.name);
  const schedule  = generateSchedule(teamNames, SCHEDULE_SEED);

  let gameId = 1;
  for (const g of schedule) {
    const hid = teamIdMap.get(g.homeTeam)!;
    const aid = teamIdMap.get(g.awayTeam)!;
    out(`INSERT INTO scheduled_games (id, season_id, week, home_team_id, away_team_id) VALUES (${gameId++}, 1, ${g.week}, ${hid}, ${aid});`);
  }
  out('');

  // ── Default lines (computer lines for all teams) ──────────────────────────
  out('-- Default lines: computer-generated for all teams');
  for (let i = 1; i < teamId; i++) {
    out(`INSERT INTO team_lines (team_id, use_computer_lines) VALUES (${i}, 1);`);
  }
  out('');

  out('-- Seed complete.');
  return lines.join('\n');
}

// ── Main ──────────────────────────────────────────────────────────────────────
const args    = process.argv.slice(2);
const local   = args.includes('--local');
const remote  = args.includes('--remote');
const sqlPath = `${process.cwd()}/scripts/seed.sql`;

console.log('Building seed SQL…');
const sql = buildSql();
writeFileSync(sqlPath, sql, 'utf8');
console.log(`Wrote ${sql.split('\n').length} lines → scripts/seed.sql`);

if (local || remote) {
  const flag = local ? '--local' : '';
  const cmd  = `npx wrangler d1 execute rwha-sim ${flag} --file=scripts/seed.sql`;
  console.log(`Running: ${cmd}`);
  try {
    execSync(cmd, { stdio: 'inherit', cwd: `${process.cwd()}/web` });
    console.log('D1 seed complete.');
  } catch (e) {
    console.error('Seed execution failed. You can apply manually:');
    console.error(`  cd web && ${cmd}`);
    process.exit(1);
  }
} else {
  console.log('');
  console.log('To apply to local D1:   npm run db:seed -- --local');
  console.log('To apply to remote D1:  npm run db:seed -- --remote');
}
